"""Export utilities for reports"""

from datetime import datetime

def generate_markdown_report(url, title, overall_score, status, category_results, performance_data):
    """Generate markdown report"""
    
    report = f"""# AI Website Grader Report

**Website:** {url}  
**Title:** {title}  
**Generated:** {datetime.now().strftime('%m/%d/%Y')}  
**Overall Score:** {overall_score}%

## Executive Summary

This report analyzes your website's readiness for AI-powered search engines, chat interfaces, and modern search algorithms. The analysis focuses on factors that influence visibility in AI overviews, voice search results, and chatbot responses.

## Score Breakdown

| Category | Score | Status |
|----------|-------|--------|
"""
    
    # Add category scores
    for category, result in category_results.items():
        category_name = category.replace('_', ' ').title()
        avg_score = round(sum(result['scores'].values()) / len(result['scores']))
        cat_status = _get_status_label(avg_score)
        report += f"| **{category_name}** | {avg_score}% | {cat_status} |\n"
    
    # Add detailed sections for each category
    for category, result in category_results.items():
        category_name = category.replace('_', ' ').title()
        avg_score = round(sum(result['scores'].values()) / len(result['scores']))
        
        report += f"\n## {category_name} ({avg_score}%)\n\n"
        
        # Key findings
        if result['findings']:
            report += "### Key Findings:\n"
            for finding in result['findings']:
                report += f"- {finding}\n"
            report += "\n"
        
        # Recommendations
        if result['recommendations']:
            report += "### Recommendations:\n"
            for rec in result['recommendations']:
                report += f"- **{rec['priority']}**: {rec['title']}\n"
                report += f"  *Implementation:* "
                for i, detail in enumerate(rec['details'], 1):
                    report += f"{i}. {detail}\n  "
                report += "\n"
        
        # Detailed scores
        report += "### Detailed Scores:\n"
        for metric, score in result['scores'].items():
            metric_name = metric.replace('_', ' ').title()
            report += f"- **{metric_name}:** {score}%\n"
        report += "\n"
    
    # Performance analysis
    if performance_data:
        report += "\n## Performance Analysis\n\n"
        
        pagespeed = performance_data.get('pagespeed', {})
        if pagespeed.get('success'):
            report += "### Core Web Vitals:\n\n"
            report += f"- **Performance Score:** {pagespeed.get('performance_score', 'N/A')}/100\n"
            report += f"- **LCP (Largest Contentful Paint):** {pagespeed.get('lcp', 'N/A')}\n"
            report += f"- **FID (First Input Delay):** {pagespeed.get('fid', 'N/A')}\n"
            report += f"- **CLS (Cumulative Layout Shift):** {pagespeed.get('cls', 'N/A')}\n\n"
        
        html_val = performance_data.get('html_validation', {})
        if html_val.get('success'):
            report += "### HTML Validation (W3C):\n\n"
            report += f"- **Status:** {'✅ Valid' if html_val.get('valid') else '❌ Invalid'}\n"
            report += f"- **Errors:** {html_val.get('error_count', 0)}\n"
            report += f"- **Warnings:** {html_val.get('warning_count', 0)}\n\n"
            
            if html_val.get('errors'):
                report += "- **Sample Issues:**\n"
                for error in html_val['errors'][:5]:
                    msg = error.get('message', 'Unknown error')
                    line = error.get('lastLine', 'N/A')
                    report += f"  - {msg} (Line {line})\n"
                report += "\n"
        
        report += f"### Accessibility Analysis:\n\n"
        report += f"- **Score:** {performance_data.get('accessibility_score', 'N/A')}/100\n"
        report += f"- **Analysis:** Based on alt text coverage, ARIA attributes, semantic HTML, and form labels\n\n"
        
        report += f"### Combined Performance Score:\n\n"
        report += f"- **Overall Score:** {performance_data.get('combined_score', 'N/A')}/100\n"
        report += f"- **Weighting:** 40% Core Web Vitals, 30% HTML Validity, 30% Accessibility\n\n"
    
    # Next steps
    report += """## Next Steps

1. **Focus on AI Optimization** - This is the most impactful area for future search visibility
2. **Implement Priority Improvements** - Start with HIGH priority recommendations
3. **Monitor Progress** - Re-run this analysis after implementing changes
4. **Stay Updated** - AI search algorithms evolve rapidly; regular audits are recommended

---

*Report generated by AI Website Grader - Optimizing content for the AI-powered search future.*
"""
    
    return report


def _get_status_label(score):
    """Get status label for score"""
    if score >= 90:
        return 'excellent'
    elif score >= 80:
        return 'good'
    elif score >= 70:
        return 'needs-improvement'
    else:
        return 'critical'


def save_markdown_report(report_content, filename):
    """Save markdown report to file"""
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report_content)
    return filename
